[variables]
NIXPACKS_NODE_VERSION = "22"
VITE_API_URL = "https://api.versacode.com.co"
VITE_APP_OWNER = "Juan David Gaitan"
VITE_APP_PHONE = "+573045384661"
VITE_APP_CONTACT = "juandavid092415@hotmail.com"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx --yes serve dist -s -l tcp://0.0.0.0:${PORT:-3000}"
